### ISSUE TITLE
nothing in /dev/intel-fpga-port.0 and /sys/class/fpga/intel-fpga-dev.0/intel-fpga-port.0/

### ISSUE THREAD

**Issue by 9qvuyc3o** [RSPwFPGAs/opae-xilinx#1]
Excuse me sir, when I build the cosim project, I have followed all the steps exactly as the readme,but in the docker step ,I cannot get the fpga device after running the install_opae_drv.sh in the two path ,and after reboot the vm and docker ,it always retured no such file or directory,I have tried many times  and installed the os and docker many times and still the same. The docker host what I use is ubuntu 16.04.6 server. And I don't have any intel fpga board in the PC.
So what's wrong maybe in my operation. Did I missed some details.
Thankyou for the time. Best regards

**Comment by aeteijeiro** [comment]
Hey 9qvuyc3o, were you able to install this without an intel board plugged in? To my knowledge desktop linux compilations do not use device trees, so it seems to me like the logical way to insert a device into sysfs is by registering it in a probe() call. However, probe() won't be called unless a device that is compatible with the driver is found... hence I'm wondering whether you were able to get it working with a Xilinx device plugged in, instead of intel.
